//! Central registry for production environment variables used by Flare IM Core.
//!
//! The current codebase still reads many variables at service config boundaries.
//! This registry makes that surface explicit so new operational knobs cannot
//! appear as undocumented string literals.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EnvVarSpec {
    pub key: &'static str,
    pub owner: EnvOwner,
    pub purpose: EnvPurpose,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EnvOwner {
    AccessGateway,
    ApiGateway,
    AdminGateway,
    Capability,
    Conversation,
    MessageIngest,
    Orchestrator,
    PushProxy,
    PushServer,
    PushWorker,
    Ops,
    SignalingOnline,
    SignalingRoute,
    Storage,
    SyncOrchestrator,
    Runtime,
    Shared,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EnvPurpose {
    Auth,
    ConfigPath,
    Database,
    Discovery,
    GatewayRuntime,
    Mq,
    Observability,
    Redis,
    ServiceEndpoint,
    TenantDefaults,
    RuntimeTuning,
    TestOnly,
}

pub const REGISTERED_ENV_VARS: &[EnvVarSpec] = &[
    env(
        "ACCESS_GATEWAY_AUTH_HOOK_SECRET",
        EnvOwner::AccessGateway,
        EnvPurpose::Auth,
    ),
    env(
        "ACCESS_GATEWAY_AUTH_HOOK_SECRET_HEADER",
        EnvOwner::AccessGateway,
        EnvPurpose::Auth,
    ),
    env(
        "ACCESS_GATEWAY_AUTH_HOOK_TIMEOUT_MS",
        EnvOwner::AccessGateway,
        EnvPurpose::Auth,
    ),
    env(
        "ACCESS_GATEWAY_AUTH_HOOK_URL",
        EnvOwner::AccessGateway,
        EnvPurpose::Auth,
    ),
    env(
        "ACCESS_GATEWAY_AUTH_MODE",
        EnvOwner::AccessGateway,
        EnvPurpose::Auth,
    ),
    env(
        "ACCESS_GATEWAY_AUTH_TIMEOUT_SECS",
        EnvOwner::AccessGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "ACCESS_GATEWAY_CONNECTION_TIMEOUT_SECS",
        EnvOwner::AccessGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "ACCESS_GATEWAY_DEFAULT_SVID",
        EnvOwner::AccessGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "ACCESS_GATEWAY_DEFAULT_TENANT_ID",
        EnvOwner::AccessGateway,
        EnvPurpose::TenantDefaults,
    ),
    env(
        "ACCESS_GATEWAY_GRPC_ENDPOINT",
        EnvOwner::AccessGateway,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "ACCESS_GATEWAY_HEARTBEAT_INTERVAL_SECS",
        EnvOwner::AccessGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "ACCESS_GATEWAY_HEARTBEAT_TIMEOUT_SECS",
        EnvOwner::AccessGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "ACCESS_GATEWAY_MAX_CONNECTIONS",
        EnvOwner::AccessGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "ACCESS_GATEWAY_SEND_TIMEOUT_SECS",
        EnvOwner::AccessGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "ACCESS_GATEWAY_SYNC_PULL_RATE_LIMIT_ENABLED",
        EnvOwner::AccessGateway,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "ACCESS_GATEWAY_SYNC_PULL_TENANT_BURST",
        EnvOwner::AccessGateway,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "ACCESS_GATEWAY_SYNC_PULL_TENANT_REQUESTS_PER_SECOND",
        EnvOwner::AccessGateway,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "ACCESS_GATEWAY_SYNC_PULL_USER_BURST",
        EnvOwner::AccessGateway,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "ACCESS_GATEWAY_SYNC_PULL_USER_REQUESTS_PER_SECOND",
        EnvOwner::AccessGateway,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "ACCESS_GATEWAY_USE_ACK_REPORT",
        EnvOwner::AccessGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "ACCESS_GATEWAY_USE_ROUTE_SERVICE",
        EnvOwner::AccessGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "BUSINESS_SERVICE_AI_ENDPOINT",
        EnvOwner::SignalingRoute,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "BUSINESS_SERVICE_CS_ENDPOINT",
        EnvOwner::SignalingRoute,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "BUSINESS_SERVICE_IM_ENDPOINT",
        EnvOwner::SignalingRoute,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "CAPABILITY_POSTGRES_ACQUIRE_TIMEOUT_SECONDS",
        EnvOwner::Capability,
        EnvPurpose::Database,
    ),
    env(
        "CAPABILITY_POSTGRES_IDLE_TIMEOUT_SECONDS",
        EnvOwner::Capability,
        EnvPurpose::Database,
    ),
    env(
        "CAPABILITY_POSTGRES_MAX_CONNECTIONS",
        EnvOwner::Capability,
        EnvPurpose::Database,
    ),
    env(
        "CAPABILITY_POSTGRES_MAX_LIFETIME_SECONDS",
        EnvOwner::Capability,
        EnvPurpose::Database,
    ),
    env(
        "CAPABILITY_POSTGRES_MIN_CONNECTIONS",
        EnvOwner::Capability,
        EnvPurpose::Database,
    ),
    env(
        "CAPABILITY_RUNTIME_CONFIG_FILE",
        EnvOwner::Capability,
        EnvPurpose::ConfigPath,
    ),
    env(
        "CONFIG_CENTER_ENDPOINT",
        EnvOwner::Capability,
        EnvPurpose::ServiceEndpoint,
    ),
    env("CONFIG_FILE", EnvOwner::Capability, EnvPurpose::ConfigPath),
    env(
        "CONVERSATION_CONFLICT_RESOLUTION",
        EnvOwner::Conversation,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "CONVERSATION_JETSTREAM_ENSURE_GROUP",
        EnvOwner::Conversation,
        EnvPurpose::Mq,
    ),
    env(
        "CONVERSATION_JETSTREAM_ENSURE_SUBJECT",
        EnvOwner::Conversation,
        EnvPurpose::Mq,
    ),
    env(
        "CONVERSATION_JETSTREAM_EVENTS_SUBJECT",
        EnvOwner::Conversation,
        EnvPurpose::Mq,
    ),
    env(
        "CONVERSATION_JETSTREAM_GROUP",
        EnvOwner::Conversation,
        EnvPurpose::Mq,
    ),
    env(
        "CONVERSATION_JETSTREAM_OPERATION_SUBJECT",
        EnvOwner::Conversation,
        EnvPurpose::Mq,
    ),
    env(
        "CONVERSATION_JETSTREAM_URL",
        EnvOwner::Conversation,
        EnvPurpose::Mq,
    ),
    env(
        "CONVERSATION_KAFKA_BROKERS",
        EnvOwner::Conversation,
        EnvPurpose::Mq,
    ),
    env(
        "CONVERSATION_KAFKA_CLIENT_ID",
        EnvOwner::Conversation,
        EnvPurpose::Mq,
    ),
    env(
        "CONVERSATION_LARGE_CONVERSATION_PRECISE_UNREAD_THRESHOLD",
        EnvOwner::Conversation,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "CONVERSATION_POLICY_ALLOW_ANONYMOUS",
        EnvOwner::Conversation,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "CONVERSATION_POLICY_ALLOW_HISTORY_SYNC",
        EnvOwner::Conversation,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "CONVERSATION_POLICY_MAX_DEVICES",
        EnvOwner::Conversation,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "CONVERSATION_POLICY_METADATA",
        EnvOwner::Conversation,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "CONVERSATION_POSTGRES_ACQUIRE_TIMEOUT_SECONDS",
        EnvOwner::Conversation,
        EnvPurpose::Database,
    ),
    env(
        "CONVERSATION_POSTGRES_IDLE_TIMEOUT_SECONDS",
        EnvOwner::Conversation,
        EnvPurpose::Database,
    ),
    env(
        "CONVERSATION_POSTGRES_MAX_CONNECTIONS",
        EnvOwner::Conversation,
        EnvPurpose::Database,
    ),
    env(
        "CONVERSATION_POSTGRES_MAX_LIFETIME_SECONDS",
        EnvOwner::Conversation,
        EnvPurpose::Database,
    ),
    env(
        "CONVERSATION_POSTGRES_MIN_CONNECTIONS",
        EnvOwner::Conversation,
        EnvPurpose::Database,
    ),
    env(
        "CONVERSATION_POSTGRES_URL",
        EnvOwner::Conversation,
        EnvPurpose::Database,
    ),
    env(
        "CONVERSATION_PRESENCE_PREFIX",
        EnvOwner::Conversation,
        EnvPurpose::Redis,
    ),
    env(
        "CONVERSATION_RECENT_MESSAGE_LIMIT",
        EnvOwner::Conversation,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "CONVERSATION_REDIS_URL",
        EnvOwner::Conversation,
        EnvPurpose::Redis,
    ),
    env(
        "CONVERSATION_SERVICE",
        EnvOwner::Conversation,
        EnvPurpose::Discovery,
    ),
    env(
        "CONVERSATION_STATE_PREFIX",
        EnvOwner::Conversation,
        EnvPurpose::Redis,
    ),
    env(
        "CONVERSATION_STORAGE_READER_SERVICE",
        EnvOwner::Conversation,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "CONVERSATION_UNREAD_PREFIX",
        EnvOwner::Conversation,
        EnvPurpose::Redis,
    ),
    env(
        "CONVERSATION_USER_CURSOR_PREFIX",
        EnvOwner::Conversation,
        EnvPurpose::Redis,
    ),
    env("DATABASE_URL", EnvOwner::Capability, EnvPurpose::Database),
    env(
        "DEFAULT_TENANT_ID",
        EnvOwner::SignalingRoute,
        EnvPurpose::TenantDefaults,
    ),
    env(
        "FLARE_ADMIN_GATEWAY_TOKEN_SECRET",
        EnvOwner::AdminGateway,
        EnvPurpose::Auth,
    ),
    env(
        "FLARE_API_GATEWAY_AUTH_HOOK_SECRET",
        EnvOwner::ApiGateway,
        EnvPurpose::Auth,
    ),
    env(
        "FLARE_API_GATEWAY_AUTH_HOOK_SECRET_HEADER",
        EnvOwner::ApiGateway,
        EnvPurpose::Auth,
    ),
    env(
        "FLARE_API_GATEWAY_AUTH_HOOK_TIMEOUT_MS",
        EnvOwner::ApiGateway,
        EnvPurpose::Auth,
    ),
    env(
        "FLARE_API_GATEWAY_AUTH_HOOK_URL",
        EnvOwner::ApiGateway,
        EnvPurpose::Auth,
    ),
    env(
        "FLARE_API_GATEWAY_AUTH_MODE",
        EnvOwner::ApiGateway,
        EnvPurpose::Auth,
    ),
    env(
        "FLARE_API_GATEWAY_GRPC_CONVERSATION_STATIC_FALLBACK",
        EnvOwner::ApiGateway,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "FLARE_API_GATEWAY_GRPC_MEDIA_STATIC_FALLBACK",
        EnvOwner::ApiGateway,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "FLARE_API_GATEWAY_GRPC_MESSAGE_INGEST_STATIC_FALLBACK",
        EnvOwner::ApiGateway,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "FLARE_API_GATEWAY_GRPC_MESSAGE_ORCHESTRATOR_STATIC_FALLBACK",
        EnvOwner::ApiGateway,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "FLARE_API_GATEWAY_SERVER_PORT",
        EnvOwner::ApiGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "FLARE_API_GATEWAY_TOKEN_SECRET",
        EnvOwner::ApiGateway,
        EnvPurpose::Auth,
    ),
    env(
        "FLARE_CONFIG_PATH",
        EnvOwner::Runtime,
        EnvPurpose::ConfigPath,
    ),
    env("FLARE_ENV", EnvOwner::Runtime, EnvPurpose::ConfigPath),
    env(
        "FLARE_MEDIA_CONTROL_GRPC_ENDPOINT",
        EnvOwner::Capability,
        EnvPurpose::ServiceEndpoint,
    ),
    env("FLARE_MQ_DEFAULT_BACKEND", EnvOwner::Shared, EnvPurpose::Mq),
    env(
        "FLARE_DLQ_REPLAY_KAFKA_BROKERS",
        EnvOwner::Ops,
        EnvPurpose::Mq,
    ),
    env(
        "FLARE_DLQ_REPLAY_KAFKA_CLIENT_ID",
        EnvOwner::Ops,
        EnvPurpose::Mq,
    ),
    env(
        "FLARE_DLQ_REPLAY_LOG",
        EnvOwner::Ops,
        EnvPurpose::Observability,
    ),
    env(
        "FLARE_DLQ_REPLAY_NATS_RETRIES",
        EnvOwner::Ops,
        EnvPurpose::Mq,
    ),
    env(
        "FLARE_DLQ_REPLAY_NATS_RETRY_BACKOFF_MS",
        EnvOwner::Ops,
        EnvPurpose::Mq,
    ),
    env(
        "FLARE_DLQ_REPLAY_NATS_TIMEOUT_MS",
        EnvOwner::Ops,
        EnvPurpose::Mq,
    ),
    env("FLARE_DLQ_REPLAY_NATS_URL", EnvOwner::Ops, EnvPurpose::Mq),
    env(
        "FLARE_DLQ_REPLAY_TENANT_ID",
        EnvOwner::Ops,
        EnvPurpose::TenantDefaults,
    ),
    env(
        "FLARE_OBJECT_STORE_PROFILE",
        EnvOwner::Runtime,
        EnvPurpose::ConfigPath,
    ),
    env(
        "FLARE_REDIS_TEST_URL",
        EnvOwner::Shared,
        EnvPurpose::TestOnly,
    ),
    env(
        "GATEWAY_COMPRESSION_ALGORITHM",
        EnvOwner::AccessGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "GATEWAY_ENABLE_ENCRYPTION",
        EnvOwner::AccessGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "GATEWAY_ENCRYPTION_KEY",
        EnvOwner::AccessGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "GATEWAY_ID",
        EnvOwner::AccessGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "GATEWAY_REGION",
        EnvOwner::AccessGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "GATEWAY_RESOLVED_CONVERSATIONS_CAPACITY",
        EnvOwner::AccessGateway,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "GRPC_PORT",
        EnvOwner::AccessGateway,
        EnvPurpose::GatewayRuntime,
    ),
    env(
        "INGEST_IDEMPOTENCY_RESERVE_TTL_SECS",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "INGEST_IDEMPOTENCY_RESULT_TTL_SECS",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MEDIA_SERVICE_ENDPOINT",
        EnvOwner::Storage,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "MESSAGE_INGEST_CAPABILITY_HOOKS_AUTO",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_DEFAULT_BUSINESS_TYPE",
        EnvOwner::MessageIngest,
        EnvPurpose::TenantDefaults,
    ),
    env(
        "MESSAGE_INGEST_DEFAULT_SENDER_TYPE",
        EnvOwner::MessageIngest,
        EnvPurpose::TenantDefaults,
    ),
    env(
        "MESSAGE_INGEST_DEFAULT_SESSION_TYPE",
        EnvOwner::MessageIngest,
        EnvPurpose::TenantDefaults,
    ),
    env(
        "MESSAGE_INGEST_DEFAULT_TENANT_ID",
        EnvOwner::MessageIngest,
        EnvPurpose::TenantDefaults,
    ),
    env(
        "MESSAGE_INGEST_EXTENSION_HOOK_MESSAGE_TYPE_ALLOWLIST",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_EXTENSION_POST_SEND_FAIL_OPEN",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_EXTENSION_POST_SEND_RETRY",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_EXTENSION_POST_SEND_TIMEOUT_MS",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_EXTENSION_PRE_SEND_RETRY",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_EXTENSION_PRE_SEND_TIMEOUT_MS",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_EXTENSION_TENANT_ALLOWLIST",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_HOOKS_CONFIG",
        EnvOwner::MessageIngest,
        EnvPurpose::ConfigPath,
    ),
    env(
        "MESSAGE_INGEST_HOOKS_CONFIG_DIR",
        EnvOwner::MessageIngest,
        EnvPurpose::ConfigPath,
    ),
    env(
        "MESSAGE_INGEST_JETSTREAM_RETRIES",
        EnvOwner::MessageIngest,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_INGEST_JETSTREAM_RETRY_BACKOFF_MS",
        EnvOwner::MessageIngest,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_INGEST_JETSTREAM_TIMEOUT_MS",
        EnvOwner::MessageIngest,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_INGEST_JETSTREAM_URL",
        EnvOwner::MessageIngest,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_INGEST_KAFKA_CLIENT_ID",
        EnvOwner::MessageIngest,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_INGEST_LARGE_CONVERSATION_MATERIALIZE_THRESHOLD",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_MESSAGE_DLQ_TOPIC",
        EnvOwner::MessageIngest,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_INGEST_MESSAGE_RETRY_DELAY_MS",
        EnvOwner::MessageIngest,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_INGEST_MESSAGE_RETRY_TOPIC",
        EnvOwner::MessageIngest,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_INGEST_METRICS_ADDRESS",
        EnvOwner::MessageIngest,
        EnvPurpose::Observability,
    ),
    env(
        "MESSAGE_INGEST_METRICS_ENABLED",
        EnvOwner::MessageIngest,
        EnvPurpose::Observability,
    ),
    env(
        "MESSAGE_INGEST_METRICS_PATH",
        EnvOwner::MessageIngest,
        EnvPurpose::Observability,
    ),
    env(
        "MESSAGE_INGEST_METRICS_PORT",
        EnvOwner::MessageIngest,
        EnvPurpose::Observability,
    ),
    env(
        "MESSAGE_INGEST_READER_ENDPOINT",
        EnvOwner::MessageIngest,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "MESSAGE_INGEST_REDIS_URL",
        EnvOwner::MessageIngest,
        EnvPurpose::Redis,
    ),
    env(
        "MESSAGE_INGEST_SESSION_SERVICE_TYPE",
        EnvOwner::MessageIngest,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "MESSAGE_INGEST_SEND_PUBLISH_TIMEOUT_MS",
        EnvOwner::MessageIngest,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_INGEST_SEND_RATE_LIMIT_ENABLED",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_SEND_RATE_LIMIT_MAX_TRACKED_KEYS",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_SEND_RATE_LIMIT_TENANT_CONVERSATION_PER_SECOND",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_SEND_RATE_LIMIT_TENANT_PER_SECOND",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_SEND_RATE_LIMIT_TENANT_SENDER_PER_SECOND",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_SEND_RATE_LIMIT_WINDOW_MS",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_WAL_HASH_KEY",
        EnvOwner::MessageIngest,
        EnvPurpose::Redis,
    ),
    env(
        "MESSAGE_INGEST_WAL_REPLAY_BATCH_LIMIT",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_WAL_REPLAY_CLAIM_LEASE_MS",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_WAL_REPLAY_ENABLED",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_WAL_REPLAY_ERROR_BACKOFF_MS",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_WAL_REPLAY_INTERVAL_MS",
        EnvOwner::MessageIngest,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_INGEST_WAL_TTL_SECONDS",
        EnvOwner::MessageIngest,
        EnvPurpose::Redis,
    ),
    env(
        "MESSAGE_ORCHESTRATOR_DEFAULT_TENANT_ID",
        EnvOwner::Orchestrator,
        EnvPurpose::TenantDefaults,
    ),
    env(
        "MESSAGE_ORCHESTRATOR_JETSTREAM_RETRIES",
        EnvOwner::Orchestrator,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_ORCHESTRATOR_JETSTREAM_RETRY_BACKOFF_MS",
        EnvOwner::Orchestrator,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_ORCHESTRATOR_JETSTREAM_TIMEOUT_MS",
        EnvOwner::Orchestrator,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_ORCHESTRATOR_JETSTREAM_URL",
        EnvOwner::Orchestrator,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_ORCHESTRATOR_INLINE_MESSAGE_PUSH_ENABLED",
        EnvOwner::Orchestrator,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_ORCHESTRATOR_KAFKA_CLIENT_ID",
        EnvOwner::Orchestrator,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_ORCHESTRATOR_MESSAGE_DLQ_TOPIC",
        EnvOwner::Orchestrator,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_ORCHESTRATOR_MESSAGE_RETRY_DELAY_MS",
        EnvOwner::Orchestrator,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_ORCHESTRATOR_MESSAGE_RETRY_TOPIC",
        EnvOwner::Orchestrator,
        EnvPurpose::Mq,
    ),
    env(
        "MESSAGE_ORCHESTRATOR_REDIS_URL",
        EnvOwner::Orchestrator,
        EnvPurpose::Redis,
    ),
    env(
        "MESSAGE_ORCHESTRATOR_LARGE_CONVERSATION_PUSH_THRESHOLD",
        EnvOwner::Orchestrator,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_ORCHESTRATOR_SESSION_SERVICE_TYPE",
        EnvOwner::Orchestrator,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "MESSAGE_ORCHESTRATOR_USER_SYNC_INDEX_MAX_CHANGES_PER_USER",
        EnvOwner::Orchestrator,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "MESSAGE_ORCHESTRATOR_USER_SYNC_INDEX_TTL_SECONDS",
        EnvOwner::Orchestrator,
        EnvPurpose::Redis,
    ),
    env(
        "ORCHESTRATOR_SERVICE",
        EnvOwner::SignalingRoute,
        EnvPurpose::ServiceEndpoint,
    ),
    env("PORT", EnvOwner::AccessGateway, EnvPurpose::GatewayRuntime),
    env("POSTGRES_URL", EnvOwner::Storage, EnvPurpose::Database),
    env(
        "PUSH_PROXY_DEVICE_TOKEN_KEY_PREFIX",
        EnvOwner::PushProxy,
        EnvPurpose::Redis,
    ),
    env(
        "PUSH_PROXY_DEVICE_TOKEN_REDIS_URL",
        EnvOwner::PushProxy,
        EnvPurpose::Redis,
    ),
    env(
        "PUSH_PROXY_JETSTREAM_RETRIES",
        EnvOwner::PushProxy,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_PROXY_JETSTREAM_RETRY_BACKOFF_MS",
        EnvOwner::PushProxy,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_PROXY_JETSTREAM_TIMEOUT_MS",
        EnvOwner::PushProxy,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_PROXY_JETSTREAM_URL",
        EnvOwner::PushProxy,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_PROXY_KAFKA_BROKERS",
        EnvOwner::PushProxy,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_PROXY_KAFKA_CLIENT_ID",
        EnvOwner::PushProxy,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_PROXY_PUSH_ENVELOPE_TOPIC",
        EnvOwner::PushProxy,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_PROXY_PUSH_OFFLINE_TOPIC",
        EnvOwner::PushProxy,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_PROXY_PUSH_ONLINE_TOPIC",
        EnvOwner::PushProxy,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_PROXY_PUSH_REQUEST_TOPIC",
        EnvOwner::PushProxy,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_PROXY_REDIS_KEY_PREFIX",
        EnvOwner::PushProxy,
        EnvPurpose::Redis,
    ),
    env(
        "PUSH_PROXY_REDIS_URL",
        EnvOwner::PushProxy,
        EnvPurpose::Redis,
    ),
    env(
        "PUSH_SERVER_CONSUMER_GROUP",
        EnvOwner::PushServer,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_SERVER_CONVERSATION_READ_ENDPOINT",
        EnvOwner::PushServer,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "PUSH_SERVER_DEFAULT_TENANT_ID",
        EnvOwner::PushServer,
        EnvPurpose::TenantDefaults,
    ),
    env(
        "PUSH_SERVER_EVENT_PING_PARTICIPANT_PAGE_SIZE",
        EnvOwner::PushServer,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "PUSH_SERVER_EVENT_PING_COALESCE_WINDOW_MS",
        EnvOwner::PushServer,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "PUSH_SERVER_JETSTREAM_RETRIES",
        EnvOwner::PushServer,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_SERVER_JETSTREAM_RETRY_BACKOFF_MS",
        EnvOwner::PushServer,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_SERVER_JETSTREAM_TIMEOUT_MS",
        EnvOwner::PushServer,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_SERVER_JETSTREAM_URL",
        EnvOwner::PushServer,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_SERVER_KAFKA_BROKERS",
        EnvOwner::PushServer,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_SERVER_KAFKA_CLIENT_ID",
        EnvOwner::PushServer,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_SERVER_ONLINE_SERVICE_ENDPOINT",
        EnvOwner::PushServer,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "PUSH_SERVER_ONLINE_STATUS_BACKEND",
        EnvOwner::PushServer,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "PUSH_SERVER_PUSH_DLQ_TOPIC",
        EnvOwner::PushServer,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_SERVER_PUSH_ENVELOPE_TOPIC",
        EnvOwner::PushServer,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_SERVER_PUSH_EVENT_TOPIC",
        EnvOwner::PushServer,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_SERVER_PUSH_MESSAGE_TOPIC",
        EnvOwner::PushServer,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_SERVER_PUSH_OFFLINE_TOPIC",
        EnvOwner::PushServer,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_SERVER_REDIS_URL",
        EnvOwner::PushServer,
        EnvPurpose::Redis,
    ),
    env(
        "PUSH_SERVER_PUSH_ONLINE_TOPIC",
        EnvOwner::PushServer,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_WORKER_CONSUMER_GROUP",
        EnvOwner::PushWorker,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_WORKER_DEVICE_TOKEN_KEY_PREFIX",
        EnvOwner::PushWorker,
        EnvPurpose::Redis,
    ),
    env(
        "PUSH_WORKER_DEVICE_TOKEN_REDIS_URL",
        EnvOwner::PushWorker,
        EnvPurpose::Redis,
    ),
    env(
        "PUSH_WORKER_EVENT_PING_DEBOUNCE_WINDOW_MS",
        EnvOwner::PushWorker,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "PUSH_WORKER_GETUI_DEFAULT_TTL_MS",
        EnvOwner::PushWorker,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "PUSH_WORKER_GETUI_REQUEST_TIMEOUT_MS",
        EnvOwner::PushWorker,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "PUSH_WORKER_JETSTREAM_RETRIES",
        EnvOwner::PushWorker,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_WORKER_JETSTREAM_RETRY_BACKOFF_MS",
        EnvOwner::PushWorker,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_WORKER_JETSTREAM_TIMEOUT_MS",
        EnvOwner::PushWorker,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_WORKER_JETSTREAM_URL",
        EnvOwner::PushWorker,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_WORKER_KAFKA_BROKERS",
        EnvOwner::PushWorker,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_WORKER_KAFKA_CLIENT_ID",
        EnvOwner::PushWorker,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_WORKER_METRICS_ADDRESS",
        EnvOwner::PushWorker,
        EnvPurpose::Observability,
    ),
    env(
        "PUSH_WORKER_METRICS_PATH",
        EnvOwner::PushWorker,
        EnvPurpose::Observability,
    ),
    env(
        "PUSH_WORKER_METRICS_PORT",
        EnvOwner::PushWorker,
        EnvPurpose::Observability,
    ),
    env(
        "PUSH_WORKER_OFFLINE_DELIVERY_BACKEND",
        EnvOwner::PushWorker,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "PUSH_WORKER_OFFLINE_OUTBOX_MAXLEN",
        EnvOwner::PushWorker,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "PUSH_WORKER_OFFLINE_OUTBOX_STREAM",
        EnvOwner::PushWorker,
        EnvPurpose::Redis,
    ),
    env(
        "PUSH_WORKER_OFFLINE_PARKING_CAPACITY",
        EnvOwner::PushWorker,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "PUSH_WORKER_OFFLINE_REDIS_URL",
        EnvOwner::PushWorker,
        EnvPurpose::Redis,
    ),
    env(
        "PUSH_WORKER_ONLINE_SERVICE_ENDPOINT",
        EnvOwner::PushWorker,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "PUSH_WORKER_PUSH_DLQ_TOPIC",
        EnvOwner::PushWorker,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_WORKER_PUSH_OFFLINE_TOPIC",
        EnvOwner::PushWorker,
        EnvPurpose::Mq,
    ),
    env(
        "PUSH_WORKER_PUSH_ONLINE_TOPIC",
        EnvOwner::PushWorker,
        EnvPurpose::Mq,
    ),
    env(
        "ROUTER_FLOW_CONTROL_ENABLED",
        EnvOwner::SignalingRoute,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "ROUTER_GROUP_FANOUT_MAX",
        EnvOwner::SignalingRoute,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "ROUTER_SESSION_QPS_LIMIT",
        EnvOwner::SignalingRoute,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "ROUTER_SHARD_COUNT",
        EnvOwner::SignalingRoute,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "SERVICE_HEARTBEAT_INTERVAL",
        EnvOwner::Runtime,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "SIGNALING_ONLINE_PRESENCE_PREFIX",
        EnvOwner::SignalingOnline,
        EnvPurpose::Redis,
    ),
    env(
        "SIGNALING_ONLINE_REDIS_TTL",
        EnvOwner::SignalingOnline,
        EnvPurpose::Redis,
    ),
    env(
        "SIGNALING_ONLINE_REDIS_URL",
        EnvOwner::SignalingOnline,
        EnvPurpose::Redis,
    ),
    env(
        "SYNC_ORCHESTRATOR_BOOTSTRAP_PAGE_CACHE_TTL_MS",
        EnvOwner::SyncOrchestrator,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "SYNC_ORCHESTRATOR_CURSOR_CACHE_CAPACITY",
        EnvOwner::SyncOrchestrator,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "SYNC_ORCHESTRATOR_REDIS_URL",
        EnvOwner::SyncOrchestrator,
        EnvPurpose::Redis,
    ),
    env(
        "STORAGE_FETCH_MAX_WAIT_MS",
        EnvOwner::Storage,
        EnvPurpose::Mq,
    ),
    env("STORAGE_FETCH_MIN_BYTES", EnvOwner::Storage, EnvPurpose::Mq),
    env(
        "STORAGE_JETSTREAM_ACK_SUBJECT",
        EnvOwner::Storage,
        EnvPurpose::Mq,
    ),
    env("STORAGE_JETSTREAM_GROUP", EnvOwner::Storage, EnvPurpose::Mq),
    env(
        "STORAGE_JETSTREAM_RETRIES",
        EnvOwner::Storage,
        EnvPurpose::Mq,
    ),
    env(
        "STORAGE_JETSTREAM_RETRY_BACKOFF_MS",
        EnvOwner::Storage,
        EnvPurpose::Mq,
    ),
    env(
        "STORAGE_JETSTREAM_TIMEOUT_MS",
        EnvOwner::Storage,
        EnvPurpose::Mq,
    ),
    env("STORAGE_JETSTREAM_URL", EnvOwner::Storage, EnvPurpose::Mq),
    env("STORAGE_KAFKA_BROKERS", EnvOwner::Storage, EnvPurpose::Mq),
    env("STORAGE_KAFKA_CLIENT_ID", EnvOwner::Storage, EnvPurpose::Mq),
    env(
        "STORAGE_MAX_POLL_RECORDS",
        EnvOwner::Storage,
        EnvPurpose::Mq,
    ),
    env(
        "STORAGE_MESSAGE_DLQ_TOPIC",
        EnvOwner::Storage,
        EnvPurpose::Mq,
    ),
    env(
        "STORAGE_MESSAGE_RETRY_DELAY_MS",
        EnvOwner::Storage,
        EnvPurpose::Mq,
    ),
    env(
        "STORAGE_MESSAGE_RETRY_TOPIC",
        EnvOwner::Storage,
        EnvPurpose::Mq,
    ),
    env(
        "STORAGE_METRICS_ADDRESS",
        EnvOwner::Storage,
        EnvPurpose::Observability,
    ),
    env(
        "STORAGE_METRICS_PATH",
        EnvOwner::Storage,
        EnvPurpose::Observability,
    ),
    env(
        "STORAGE_METRICS_PORT",
        EnvOwner::Storage,
        EnvPurpose::Observability,
    ),
    env(
        "STORAGE_POSTGRES_ACQUIRE_TIMEOUT_SECONDS",
        EnvOwner::Storage,
        EnvPurpose::Database,
    ),
    env(
        "STORAGE_POSTGRES_IDLE_TIMEOUT_SECONDS",
        EnvOwner::Storage,
        EnvPurpose::Database,
    ),
    env(
        "STORAGE_POSTGRES_MAX_CONNECTIONS",
        EnvOwner::Storage,
        EnvPurpose::Database,
    ),
    env(
        "STORAGE_POSTGRES_MAX_LIFETIME_SECONDS",
        EnvOwner::Storage,
        EnvPurpose::Database,
    ),
    env(
        "STORAGE_POSTGRES_MIN_CONNECTIONS",
        EnvOwner::Storage,
        EnvPurpose::Database,
    ),
    env(
        "STORAGE_POSTGRES_URL",
        EnvOwner::Storage,
        EnvPurpose::Database,
    ),
    env(
        "STORAGE_READER_DEFAULT_RANGE_SECONDS",
        EnvOwner::Storage,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "STORAGE_READER_GRPC_ADDR",
        EnvOwner::Storage,
        EnvPurpose::ServiceEndpoint,
    ),
    env(
        "STORAGE_READER_MAX_PAGE_SIZE",
        EnvOwner::Storage,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "STORAGE_REDIS_HOT_TAIL_LIMIT",
        EnvOwner::Storage,
        EnvPurpose::RuntimeTuning,
    ),
    env(
        "STORAGE_REDIS_HOT_TTL_SECONDS",
        EnvOwner::Storage,
        EnvPurpose::Redis,
    ),
    env(
        "STORAGE_REDIS_IDEMPOTENCY_TTL_SECONDS",
        EnvOwner::Storage,
        EnvPurpose::Redis,
    ),
    env(
        "STORAGE_REDIS_MESSAGE_CACHE_TTL_SECONDS",
        EnvOwner::Storage,
        EnvPurpose::Redis,
    ),
    env(
        "STORAGE_REDIS_SESSION_CACHE_TTL_SECONDS",
        EnvOwner::Storage,
        EnvPurpose::Redis,
    ),
    env("STORAGE_REDIS_URL", EnvOwner::Storage, EnvPurpose::Redis),
    env("STORAGE_WAL_HASH_KEY", EnvOwner::Storage, EnvPurpose::Redis),
    env(
        "STORAGE_WRITER_METRICS_ADDRESS",
        EnvOwner::Storage,
        EnvPurpose::Observability,
    ),
    env(
        "STORAGE_WRITER_METRICS_PATH",
        EnvOwner::Storage,
        EnvPurpose::Observability,
    ),
    env(
        "STORAGE_WRITER_METRICS_PORT",
        EnvOwner::Storage,
        EnvPurpose::Observability,
    ),
    env(
        "TENANT_ID",
        EnvOwner::Capability,
        EnvPurpose::TenantDefaults,
    ),
];

pub fn registered_env_var(key: &str) -> Option<&'static EnvVarSpec> {
    REGISTERED_ENV_VARS.iter().find(|spec| spec.key == key)
}

const fn env(key: &'static str, owner: EnvOwner, purpose: EnvPurpose) -> EnvVarSpec {
    EnvVarSpec {
        key,
        owner,
        purpose,
    }
}
