[package]
name = "flare-im-seq"
version.workspace = true
edition.workspace = true

[lib]
name = "flare_im_seq"
path = "src/lib.rs"

[dependencies]
flare-server-core = { workspace = true }
rand = { workspace = true }
redis = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
